// This file will be generated by the CLI based on selected modules
// Base version: simple storage without MMKV

export const storage = {
  getItem: (name: string) => {
    // Fallback implementation
    return null;
  },
  setItem: (name: string, value: string) => {
    // Fallback implementation
  },
  removeItem: (name: string) => {
    // Fallback implementation
  },
};
